/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import presentacion.controlador.ControladorVentanaPrincipal;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import org.jfree.chart.JFreeChart;

/**
 *
 * @author Estudiantes
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private final Modelo modelo;
    private ControladorVentanaPrincipal control;

    public ControladorVentanaPrincipal getControl() {
        if(control == null){
            control = new ControladorVentanaPrincipal(this);
        }
        return control;
    }

    public void setControl(ControladorVentanaPrincipal control) {
        this.control = control;
    }
    
     public Modelo getModelo() {
        return modelo;
    }
    
    
    /**
     * Creates new form Vista
     */
    public VentanaPrincipal(Modelo s) {
        modelo = s;
        initComponents();
        capturarEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSaldos = new javax.swing.JPanel();
        jLabelSaldos = new javax.swing.JLabel();
        jLabelBilletera = new javax.swing.JLabel();
        jLabelCuenta = new javax.swing.JLabel();
        jLabelValorBilletera = new javax.swing.JLabel();
        jLabelValorCuenta = new javax.swing.JLabel();
        jPanelGastos = new javax.swing.JPanel();
        jLabelGastos = new javax.swing.JLabel();
        jLabelValorGastos = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelIngresor = new javax.swing.JLabel();
        jLabelValorIngresos = new javax.swing.JLabel();
        jButtonMovimientos = new javax.swing.JButton();
        jButtonReportes = new javax.swing.JButton();
        jPanelTorta = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelSaldos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelSaldos.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelSaldos.setText("Saldos");

        jLabelBilletera.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelBilletera.setText("Billetera");

        jLabelCuenta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCuenta.setText("Cuenta");

        jLabelValorBilletera.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N

        jLabelValorCuenta.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N

        javax.swing.GroupLayout jPanelSaldosLayout = new javax.swing.GroupLayout(jPanelSaldos);
        jPanelSaldos.setLayout(jPanelSaldosLayout);
        jPanelSaldosLayout.setHorizontalGroup(
            jPanelSaldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaldosLayout.createSequentialGroup()
                .addGroup(jPanelSaldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSaldosLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabelSaldos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSaldosLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanelSaldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSaldosLayout.createSequentialGroup()
                                .addComponent(jLabelCuenta)
                                .addGap(25, 25, 25)
                                .addComponent(jLabelValorCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelSaldosLayout.createSequentialGroup()
                                .addComponent(jLabelBilletera)
                                .addGap(22, 22, 22)
                                .addComponent(jLabelValorBilletera, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSaldosLayout.setVerticalGroup(
            jPanelSaldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaldosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelSaldos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelSaldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSaldosLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabelBilletera))
                    .addGroup(jPanelSaldosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabelValorBilletera, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelSaldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValorCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCuenta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelGastos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelGastos.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabelGastos.setText("Gastos");

        jLabelValorGastos.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N

        javax.swing.GroupLayout jPanelGastosLayout = new javax.swing.GroupLayout(jPanelGastos);
        jPanelGastos.setLayout(jPanelGastosLayout);
        jPanelGastosLayout.setHorizontalGroup(
            jPanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGastosLayout.createSequentialGroup()
                .addGroup(jPanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGastosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelGastos))
                    .addGroup(jPanelGastosLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabelValorGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelGastosLayout.setVerticalGroup(
            jPanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGastosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGastos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelValorGastos, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelIngresor.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabelIngresor.setText("Ingresos");

        jLabelValorIngresos.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIngresor)
                .addGap(18, 18, 18)
                .addComponent(jLabelValorIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIngresor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelValorIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonMovimientos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonMovimientos.setText("Movimientos");

        jButtonReportes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonReportes.setText("Ver Graficos");

        javax.swing.GroupLayout jPanelTortaLayout = new javax.swing.GroupLayout(jPanelTorta);
        jPanelTorta.setLayout(jPanelTortaLayout);
        jPanelTortaLayout.setHorizontalGroup(
            jPanelTortaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelTortaLayout.setVerticalGroup(
            jPanelTortaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelSaldos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanelGastos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jButtonMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelTorta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelTorta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelSaldos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMovimientos;
    private javax.swing.JButton jButtonReportes;
    private javax.swing.JLabel jLabelBilletera;
    private javax.swing.JLabel jLabelCuenta;
    private javax.swing.JLabel jLabelGastos;
    private javax.swing.JLabel jLabelIngresor;
    private javax.swing.JLabel jLabelSaldos;
    private javax.swing.JLabel jLabelValorBilletera;
    private javax.swing.JLabel jLabelValorCuenta;
    private javax.swing.JLabel jLabelValorGastos;
    private javax.swing.JLabel jLabelValorIngresos;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelGastos;
    private javax.swing.JPanel jPanelSaldos;
    private javax.swing.JPanel jPanelTorta;
    // End of variables declaration//GEN-END:variables
    private JFreeChart jTorta;

    public JFreeChart getjTorta() {
        return jTorta;
    }

    public void setjTorta(JFreeChart jTorta) {
        this.jTorta = jTorta;
    }
    
    

    public JLabel getjLabelValorBilletera() {
        return jLabelValorBilletera;
    }

    public void setjLabelValorBilletera(JLabel jLabelValorBilletera) {
        this.jLabelValorBilletera = jLabelValorBilletera;
    }

    public JLabel getjLabelValorGastos() {
        return jLabelValorGastos;
    }

    public void setjLabelValorGastos(JLabel jLabelValorGastos) {
        this.jLabelValorGastos = jLabelValorGastos;
    }

    public JLabel getjLabelValorIngresos() {
        return jLabelValorIngresos;
    }

    public void setjLabelValorIngresos(JLabel jLabelValorIngresos) {
        this.jLabelValorIngresos = jLabelValorIngresos;
    }

    public JLabel getjLabelValorCuenta() {
        return jLabelValorCuenta;
    }

    public void setjLabelValorCuenta(JLabel jLabelValorCuenta) {
        this.jLabelValorCuenta = jLabelValorCuenta;
    }

    public JButton getjButtonMovimientos() {
        return jButtonMovimientos;
    }

    public void setjButtonMovimientos(JButton jButtonMovimientos) {
        this.jButtonMovimientos = jButtonMovimientos;
    }
    public JButton getjButtonReportes() {
        return jButtonReportes;
    }

    public void setjButtonReportes(JButton jButtonReportes) {
        this.jButtonReportes = jButtonReportes;
    }

    public JPanel getjPanelTorta() {
        return jPanelTorta;
    }

    public void setjPanelTorta(JPanel jPanelTorta) {
        this.jPanelTorta = jPanelTorta;
    }

    private void capturarEventos() {
        jButtonMovimientos.addActionListener(getControl());
        jButtonReportes.addActionListener(getControl());
    }
}
