/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import presentacion.controlador.ControladorVentanaCategorias;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Estudiantes
 */
public class VentanaCategorias extends javax.swing.JFrame {

    private final Modelo modelo;
    private ControladorVentanaCategorias control;
    
    public ControladorVentanaCategorias getControl() {
        if(control == null){
            control = new ControladorVentanaCategorias(this);
        }
        return control;
    }

    public void setControl(ControladorVentanaCategorias control) {
        this.control = control;
    }
    
     public Modelo getModelo() {
        return modelo;
    }
    
    /**
     * Creates new form Vista
     */
    public VentanaCategorias(Modelo s) {
        modelo = s;
        initComponents();
        capturarEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSaldos = new javax.swing.JPanel();
        jLabelRegistro = new javax.swing.JLabel();
        jLabelIdMovimiento = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jTextFechaMovimiento = new javax.swing.JTextField();
        jTextIdMovimiento = new javax.swing.JTextField();
        jLabelCategoria = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelSaldos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelRegistro.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelRegistro.setText("Categorias");

        jLabelIdMovimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelIdMovimiento.setText("Id Categoria");

        jLabelFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelFecha.setText("Nombre Categoria");

        jTextIdMovimiento.setEditable(false);

        jLabelCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCategoria.setText("Tipo Categoria");

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelSaldosLayout = new javax.swing.GroupLayout(jPanelSaldos);
        jPanelSaldos.setLayout(jPanelSaldosLayout);
        jPanelSaldosLayout.setHorizontalGroup(
            jPanelSaldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaldosLayout.createSequentialGroup()
                .addGroup(jPanelSaldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSaldosLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanelSaldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelSaldosLayout.createSequentialGroup()
                                .addComponent(jLabelFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFechaMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelSaldosLayout.createSequentialGroup()
                                .addGroup(jPanelSaldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelIdMovimiento)
                                    .addComponent(jLabelCategoria))
                                .addGap(109, 109, 109)
                                .addGroup(jPanelSaldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextIdMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelSaldosLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSaldosLayout.setVerticalGroup(
            jPanelSaldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaldosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanelSaldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdMovimiento)
                    .addComponent(jTextIdMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSaldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha)
                    .addComponent(jTextFechaMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanelSaldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCategoria)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButtonRegistrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRegistrar.setText("Registrar");

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setToolTipText("");

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditar.setText("Editar");

        jButtonEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelSaldos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSaldos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelIdMovimiento;
    private javax.swing.JLabel jLabelRegistro;
    private javax.swing.JPanel jPanelSaldos;
    private javax.swing.JTextField jTextFechaMovimiento;
    private javax.swing.JTextField jTextIdMovimiento;
    // End of variables declaration//GEN-END:variables

    private void capturarEventos() {
        jButtonBuscar.addActionListener(getControl());
        jButtonEditar.addActionListener(getControl());
        jButtonEliminar.addActionListener(getControl());
        jButtonBuscar.addActionListener(getControl());
    }

    public JTextField getjTextField1() {
        return jTextFechaMovimiento;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextFechaMovimiento = jTextField1;
    }

    public JTextField getjTextField2() {
        return jTextIdMovimiento;
    }

    public void setjTextField2(JTextField jTextField2) {
        this.jTextIdMovimiento = jTextField2;
    }

    public JComboBox<String> getjComboBoxCategoria() {
        return jComboBoxCategoria;
    }

    public void setjComboBoxCategoria(JComboBox<String> jComboBoxCategoria) {
        this.jComboBoxCategoria = jComboBoxCategoria;
    }

    public JTextField getjTextFechaMovimiento() {
        return jTextFechaMovimiento;
    }

    public void setjTextFechaMovimiento(JTextField jTextFechaMovimiento) {
        this.jTextFechaMovimiento = jTextFechaMovimiento;
    }

    public JTextField getjTextIdMovimiento() {
        return jTextIdMovimiento;
    }

    public void setjTextIdMovimiento(JTextField jTextIdMovimiento) {
        this.jTextIdMovimiento = jTextIdMovimiento;
    }

    public JButton getjButtonBuscar() {
        return jButtonBuscar;
    }

    public void setjButtonBuscar(JButton jButtonBuscar) {
        this.jButtonBuscar = jButtonBuscar;
    }

    public JButton getjButtonEditar() {
        return jButtonEditar;
    }

    public void setjButtonEditar(JButton jButtonEditar) {
        this.jButtonEditar = jButtonEditar;
    }

    public JButton getjButtonEliminar() {
        return jButtonEliminar;
    }

    public void setjButtonEliminar(JButton jButtonEliminar) {
        this.jButtonEliminar = jButtonEliminar;
    }

    public JButton getjButtonRegistrar() {
        return jButtonRegistrar;
    }

    public void setjButtonRegistrar(JButton jButtonRegistrar) {
        this.jButtonRegistrar = jButtonRegistrar;
    }   
}
