/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import presentacion.controlador.ControladorVentanaReportes;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Estudiantes
 */
public class VentanaReportes extends javax.swing.JFrame {

    private  DefaultTableModel modeloTabla;

    

    public DefaultTableModel getModeloTabla() {
        return modeloTabla;
    }

    public void setModeloTabla(DefaultTableModel modeloTabla) {
        this.modeloTabla = modeloTabla;
    }
    
    private final Modelo modelo;
    private ControladorVentanaReportes control;

    public ControladorVentanaReportes getControl() {
        if(control == null){
            control = new ControladorVentanaReportes(this);
        }
        return control;
    }

    public void setControl(ControladorVentanaReportes control) {
        this.control = control;
    }
    
     public Modelo getModelo() {
        return modelo;
    }
    
    
    /**
     * Creates new form Vista
     */
    public VentanaReportes(Modelo s) {
        modelo = s;
        initComponents();
        capturarEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioIngresos = new javax.swing.JRadioButton();
        jRadioCategoria = new javax.swing.JRadioButton();
        jRadioCuenta = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioIngresos.setText("Ingresos vs Gastos");
        jRadioIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioIngresosActionPerformed(evt);
            }
        });

        jRadioCategoria.setText("Por Categoria");

        jRadioCuenta.setText("Por Cuenta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioIngresos)
                .addGap(18, 18, 18)
                .addComponent(jRadioCategoria)
                .addGap(18, 18, 18)
                .addComponent(jRadioCuenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioIngresos)
                    .addComponent(jRadioCategoria)
                    .addComponent(jRadioCuenta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioIngresosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioCategoria;
    private javax.swing.JRadioButton jRadioCuenta;
    private javax.swing.JRadioButton jRadioIngresos;
    // End of variables declaration//GEN-END:variables

    private void capturarEventos() {
        jRadioCategoria.addActionListener(getControl());
        jRadioCuenta.addActionListener(getControl());
        jRadioIngresos.addActionListener(getControl());
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public ButtonGroup getButtonGroup2() {
        return buttonGroup2;
    }

    public void setButtonGroup2(ButtonGroup buttonGroup2) {
        this.buttonGroup2 = buttonGroup2;
    }

    public ButtonGroup getButtonGroup3() {
        return buttonGroup3;
    }

    public void setButtonGroup3(ButtonGroup buttonGroup3) {
        this.buttonGroup3 = buttonGroup3;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JRadioButton getjRadioCategoria() {
        return jRadioCategoria;
    }

    public void setjRadioCategoria(JRadioButton jRadioCategoria) {
        this.jRadioCategoria = jRadioCategoria;
    }

    public JRadioButton getjRadioCuenta() {
        return jRadioCuenta;
    }

    public void setjRadioCuenta(JRadioButton jRadioCuenta) {
        this.jRadioCuenta = jRadioCuenta;
    }

    public JRadioButton getjRadioIngresos() {
        return jRadioIngresos;
    }

    public void setjRadioIngresos(JRadioButton jRadioIngresos) {
        this.jRadioIngresos = jRadioIngresos;
    }
}
